// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/list-projects.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.3";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^3.25.76";
function sb(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_projects_default = defineTool({
  name: "list_projects",
  title: "Listar projetos",
  description: "Lista os projetos de marmoraria do usu\xE1rio autenticado (mais recentes primeiro).",
  inputSchema: {
    limit: z.number().int().min(1).max(100).default(20).describe("M\xE1ximo de projetos a retornar."),
    status: z.string().optional().describe("Filtrar por status (opcional).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    let q = sb(ctx).from("projects").select("*").order("created_at", { ascending: false }).limit(limit);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { projects: data }
    };
  }
});

// src/lib/mcp/tools/list-clients.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.99.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^3.25.76";
function sb2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_clients_default = defineTool2({
  name: "list_clients",
  title: "Listar clientes",
  description: "Lista os clientes cadastrados do usu\xE1rio autenticado, com busca opcional por nome.",
  inputSchema: {
    search: z2.string().optional().describe("Texto para buscar no nome do cliente."),
    limit: z2.number().int().min(1).max(100).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    let q = sb2(ctx).from("clients").select("*").order("created_at", { ascending: false }).limit(limit);
    if (search) q = q.ilike("name", `%${search}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { clients: data }
    };
  }
});

// src/lib/mcp/tools/list-quotes.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.99.3";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z3 } from "npm:zod@^3.25.76";
function sb3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_quotes_default = defineTool3({
  name: "list_quotes",
  title: "Listar or\xE7amentos",
  description: "Lista os or\xE7amentos do usu\xE1rio autenticado (mais recentes primeiro).",
  inputSchema: {
    limit: z3.number().int().min(1).max(100).default(20),
    client_id: z3.string().uuid().optional().describe("Filtrar por cliente.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, client_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    let q = sb3(ctx).from("quotes").select("*").order("created_at", { ascending: false }).limit(limit);
    if (client_id) q = q.eq("client_id", client_id);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { quotes: data }
    };
  }
});

// src/lib/mcp/tools/list-stones.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.99.3";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z4 } from "npm:zod@^3.25.76";
function sb4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_stones_default = defineTool4({
  name: "list_stones",
  title: "Listar pedras do mostru\xE1rio",
  description: "Lista as pedras (m\xE1rmores, quartzos, quartzitos) vis\xEDveis para o usu\xE1rio autenticado.",
  inputSchema: {
    search: z4.string().optional().describe("Buscar por nome da pedra."),
    category: z4.string().optional().describe("Categoria (marmore, quartzo, quartzito, etc)."),
    limit: z4.number().int().min(1).max(100).default(30)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, category, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    let q = sb4(ctx).from("stones").select("*").order("name").limit(limit);
    if (search) q = q.ilike("name", `%${search}%`);
    if (category) q = q.eq("category", category);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { stones: data }
    };
  }
});

// src/lib/mcp/tools/create-client.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.99.3";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z5 } from "npm:zod@^3.25.76";
function sb5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_client_default = defineTool5({
  name: "create_client",
  title: "Criar cliente",
  description: "Cadastra um novo cliente para o usu\xE1rio autenticado.",
  inputSchema: {
    name: z5.string().trim().min(1).describe("Nome completo do cliente."),
    email: z5.string().email().optional(),
    phone: z5.string().optional().describe("Telefone (com DDD)."),
    address: z5.string().optional(),
    notes: z5.string().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const { data, error } = await sb5(ctx).from("clients").insert({ ...input, user_id: ctx.getUserId() }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Cliente criado: ${data.name} (${data.id})` }],
      structuredContent: { client: data }
    };
  }
});

// src/lib/mcp/tools/create-quote.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.99.3";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z6 } from "npm:zod@^3.25.76";
function sb6(ctx) {
  return createClient6(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_quote_default = defineTool6({
  name: "create_quote",
  title: "Criar or\xE7amento",
  description: "Cria um novo or\xE7amento (quote) no M\xE1rmoreProart para o usu\xE1rio autenticado. Salva os dados via Supabase respeitando RLS (owner_id = usu\xE1rio logado).",
  inputSchema: {
    client_name: z6.string().trim().min(1).describe("Nome do cliente."),
    client_whatsapp: z6.string().optional().describe("WhatsApp do cliente (com DDD, ex: +5511999999999)."),
    environment_type: z6.string().optional().describe("Tipo de ambiente (ex: cozinha, banheiro, \xE1rea externa)."),
    stone_type: z6.string().optional().describe("Tipo de pedra (ex: m\xE1rmore, quartzo, quartzito)."),
    estimated_value: z6.number().nonnegative().optional().describe("Valor estimado em reais."),
    status: z6.enum(["aguardando", "aprovado", "recusado", "expirado"]).optional().describe("Status do or\xE7amento. Padr\xE3o: aguardando."),
    sent_date: z6.string().optional().describe("Data de envio no formato YYYY-MM-DD. Padr\xE3o: hoje."),
    follow_up_date: z6.string().optional().describe("Data para follow-up no formato YYYY-MM-DD."),
    observations: z6.string().optional().describe("Observa\xE7\xF5es internas sobre o or\xE7amento.")
  },
  annotations: {
    readOnlyHint: false,
    destructiveHint: false,
    idempotentHint: false,
    openWorldHint: false
  },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const payload = {
      owner_id: ctx.getUserId(),
      client_name: input.client_name,
      client_whatsapp: input.client_whatsapp ?? null,
      environment_type: input.environment_type ?? null,
      stone_type: input.stone_type ?? null,
      estimated_value: input.estimated_value ?? 0,
      status: input.status ?? "aguardando",
      observations: input.observations ?? null,
      follow_up_date: input.follow_up_date ?? null
    };
    if (input.sent_date) payload.sent_date = input.sent_date;
    const { data, error } = await sb6(ctx).from("quotes").insert(payload).select().single();
    if (error) {
      return {
        content: [{ type: "text", text: `Erro ao criar or\xE7amento: ${error.message}` }],
        isError: true
      };
    }
    return {
      content: [
        {
          type: "text",
          text: `Or\xE7amento criado para "${data.client_name}" (id: ${data.id}, valor estimado: R$ ${Number(
            data.estimated_value ?? 0
          ).toFixed(2)}, status: ${data.status}).`
        }
      ],
      structuredContent: { quote: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "xbyewjvfrshemjvtgacz";
var mcp_default = defineMcp({
  name: "marmoreproart-mcp",
  title: "M\xE1rmoreProart",
  version: "0.1.0",
  instructions: "Ferramentas do M\xE1rmoreProart (gest\xE3o de marmoraria). Use list_projects, list_clients, list_quotes e list_stones para consultar dados do usu\xE1rio logado. Use create_client para cadastrar novos clientes e create_quote para criar novos or\xE7amentos. Todos os dados respeitam as permiss\xF5es do usu\xE1rio (RLS).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_projects_default, list_clients_default, list_quotes_default, list_stones_default, create_client_default, create_quote_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
